[ActionWheel.WheelEntry_Monkette_DefenseBoost ActionWheelEntry]
ToolTipDescription="提升附近所有友方英雄专门召唤的防御单位的伤害、攻击速度和攻击范围。"

[ActionWheel.WheelEntry_Monkette_EnemyDrain ActionWheelEntry]
ToolTipDescription="降低附近敌人的力量、抗性和移动速度！"

[Abilities.PlayerAbilityDefenseBoost DunDefPlayerAbility_DefenseBoost]
DescriptiveName="防御塔强化"

[Abilities.PlayerAbilityEnemyDrain DunDefPlayerAbility_EnemyDrain]
DescriptiveName="敌人削弱"